package com.kenneth.todobackend.todolist;

import com.kenneth.todobackend.todolist.ToDoList;

import javax.persistence.*;

// Definte as entity for JPA to handle things
@Entity
// Define table name unless JPA autogenerated is fine
@Table(name="items")
public class ListItem {

  // define id
  @Id
  // Generate value, define a given strategy
  @GeneratedValue(strategy = GenerationType.AUTO)
  private Integer id;
  private String message;
  private boolean isComplete = false;

  // define a many to one mapping
  @ManyToOne
  // specify the property on the other entity to map with
  @JoinColumn(name="list_id")
  private ToDoList list;

  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public boolean isComplete() {
    return isComplete;
  }

  public void setComplete(boolean complete) {
    isComplete = complete;
  }

  public ToDoList getList() {
    return list;
  }

  public void setList(ToDoList list) {
    this.list = list;
  }
}
